api_port: 5000
batch_size: 1000
deployment_name: model_label_2_20250629_113740
deployment_platform: local
enable_a_b_testing: false
enable_monitoring: true
model_path: deployments\model_label_2_20250629_113740
scaling_config: null
